### ISSUE TITLE
Breaking dialogue across pages

### ISSUE THREAD

**Issue by rnkn** [JohnPate/Screenplay#1]
It would be great if dialogue could break across pages with the standard `(MORE)` and `(CONT'D)`. This would necessitate a rewrite of the `dialogue` environment but I think it would be worthwhile.

I've done a bit of research, and I think the solution lies in using the `everyshi` package in an implementation similar to this: http://tex.stackexchange.com/a/63847/64528

Unfortunately my currently knowledge of LaTeX is not such that I can translate this across for a patch.

Thoughts?

**Comment by JohnPate** [comment]
On Fri, 27 Feb 2015, Paul Rankin wrote:

> It would be great if dialogue could break across pages with the standard 
> `(MORE)` and `(CONT'D)`. This would necessitate a rewrite of the 
> `dialogue` environment but I think it would be worthwhile.
> 
> I've done a bit of research, and I think the solution lies in using the 
> `everyshi` package in an implementation similar to this: 
> http://tex.stackexchange.com/a/63847/64528
> 
> Unfortunately my currently knowledge of LaTeX is not such that I can 
> translate this across for a patch.
> 
> Thoughts?

```
Thanks for your input.  It's a while since I worked on Screenplay 
```

and I can't say I'm familiar with the `everyshi' package.

```
There is currently the \dialbreak macro for when you must force 
```

page breaks in dialogue - see p42/43 of my example screenplay 
``Sacrifice'' for it in action -

http://dvc.org.uk/sacrific.txt/sacrifice.pdf

```
Preferably there shouldn't be page breaks in dialogue.  I suppose 
```

in some particularly talky scene it might get to be a chore but in my 
opinion putting manual page breaks in after you've completely finished the 
screenplay is probably the best (and the LaTeX) way of doing it.

```
If you're not thoroughly familiar with using LaTeX I'd like to 
```

emphasis that page breaks aren't things you worry about until you have 
utterly and completely finished your work.  You will have to put some page 
breaks in manually to make it work just right.

```
If I get a chance to look at it I will but I put quite a bit of 
```

thought about what todo about page breaks in dialogue, if I recall, and 
came to the conclusion that \dialbreak was optimal solution all things 
considered.  Also, it has the side of effect of making you think about 
cutting down unnecessary dialogue... which, IMHO, is generally a good 
thing.

```
Hope this helps.
```

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-|message from the cookie daemon|

Life is much more manageable when thought of as a scavenger
hunt as opposed to a surprise party.

## 

John Pate johnny@dvc.org.uk
Edinburgh, Scotland (home PC)
Disclaimer: I've probably changed my opinions by the time you read this
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

**Comment by rnkn** [comment]
Thanks for the quick reply.

I'm actually wanting to use Screenplay as an output from [Fountain Mode](https://github.com/rnkn/fountain-mode) for Emacs. This package uses Fountain, a very basic plaintext markup similar to Markdown, which is intended for use as the source version of a writer's screenplay. The package implementation of Screenplay would use LaTeX as an intermediary for PDF output, so the user wouldn't be editing LaTeX directly.

If you get a chance to have a look at `everyshi` and still decide against an automated page-break implementation, I'd still love to get your thoughts on how it would be accomplished.

**Comment by JohnPate** [comment]
On Sat, 28 Feb 2015, Paul Rankin wrote:

> I'm actually wanting to use Screenplay as an output from [Fountain 
> Mode](https://github.com/rnkn/fountain-mode) for Emacs. This package 
> uses Fountain, a very basic plaintext markup similar to Markdown, which 
> is intended for use as the source version of a writer's screenplay. The 
> package implementation of Screenplay would use LaTeX as an intermediary 
> for PDF output, so the user wouldn't be editing LaTeX directly.
> 
> If you get a chance to have a look at `everyshi` and still decide 
> against an automated page-break implementation, I'd still love to get 
> your thoughts on how it would be accomplished.

```
OK, I understand what you're wanting now.  It's not really what 
```

Screenplay was designed for... or LaTeX for that matter!

```
At the moment I'm pretty busy with family commitments but I'll 
```

see if I can find time to take a look at it (by which I mean the issue of 
doing something about automating page breaks in dialogue text). 
Actually, I think you'll find LaTeX isn't as intimidating as it looks if 
you're comfortable coding, it's just the old-style \ and } that make it 
look a bit formidable.

```
Had a quick look at everyshi.  Is your theory to enable page break 
```

in the dialogue environment and if that happens use everyshi to put in the 
relevant headers?  It would be interesting to see how that works in 
practise, the downside is would lead to more unnecessary breaks in 
dialogue sections, given that when reading a screenplay page it is 
preferred to err on the side of not breaking dialogue even if it's at the 
expense of whitespace.  This isn't just to make it easier to read, it's 
because dialogue takes more screen time - a properly formatted draft 
screenplay can be timed (very roughly of course) by page counting.  At 
least, that's the theory - whether it's really true in practise is another 
matter.  It's probably true for a professionally written one, I imagine.

```
We're still trying to emulate what people used to do with 
```

typewriters.  What you've got to remember is a typewriter is rather more 
sophisticated than a computer.  What I mean by that is that a typewriter 
is more directly an extension of the person's mind than a computerised 
typesetting system: the typist makes conscious and unconscious decisions 
about each character that lands on the page and it's relationship to all 
the others.  Sometimes less is more.  A computer is just a dumb machine 
with no soul... and because of that we've all lost a little bit of our 
souls.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-|message from the cookie daemon|

Who knew shooting zombies could be so educational.

## 

John Pate johnny@dvc.org.uk
Edinburgh, Scotland (home PC)
Disclaimer: I've probably changed my opinions by the time you read this
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

**Comment by rnkn** [comment]
Hey John, I've had some minor progress, although it's a little two-steps-forward-one-step-back. Here's what I've been working on: https://www.sharelatex.com/project/54ed9180966959cb7fdbde8e

I've discovered that because of the TeX asynchronous way of page-breaking, the only way to reliably save the character name is with `\mark` then referencing `\botmark`. So that solves one small part of it, as every time a real `CHARACTER (CONT'D)` break occurs, it's the correct character. But...

The problem is I can't seem to figure out is how to _really_ make TeX know when a page break occurs within the `dialog` environment. First I tried `\newif\ifWithinDialog` then setting `\WithinDialogtrue` at the beginning of the environment, then `\WithinDialogfalse` at the end, but it doesn't appear reliable. It seems like TeX will start laying out the environment, set the conditional `\WithinDialogtrue`, then figure out there's not enough room, then push it onto the next page, which creates a false "break".

Given the purported reliability of `\mark` I figured the better option was to save the character name at the beginning of the environment then set `\mark` to `\empty` at the end. Still no luck.

**Comment by JohnPate** [comment]
On Sat, 4 Apr 2015, Paul Rankin wrote:

> Given the purported reliability of `\mark` I figured the better option 
> was to save the character name at the beginning of the environment then 
> set `\mark` to `\empty` at the end. Still no luck.

```
I'll try and take a look at your code.  But, I know what you're 
```

talking about... I spent quite a while trying to figure out if LaTeX would 
remember the character name for me, so you've actually got a bit further 
on than me.

```
I think what it is that I banged my head against the fact that 
```

it's a macro language not a programming language and, by its nature, it 
works in a different way because of that.

```
I consoled myself with the fact that with any LaTeX document I 
```

ever did that was non-trivial I always had to put in some manual page 
breaks as a final step to get it right because... that's just the way it 
is.  I think you'd need to write the print output in Postscript and write 
a pretty fancy page-break algorithm to get it to work the way you'd really 
want.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-|message from the cookie daemon|

They make their living by manipulating people with oratory
and promises.  Such people do not say what they believe, they
say what they need to to get what they want.

## 

John Pate johnny@dvc.org.uk
Edinburgh, Scotland (home PC)
Disclaimer: I've probably changed my opinions by the time you read this
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

**Comment by rnkn** [comment]
I am sure it's possible because I've seen Celtx do it, but they use a server-side LaTeX typesetting, so _how_ remains a frustrating mystery!

Anyway, let me know your thoughts if you get a chance to take a look.
